### ISSUE TITLE
Search Not Working Anymore

### ISSUE THREAD

**Issue by FristyFlakes** [Anandpskerala/TorrentSearcherBot#4]
When Searching It Doesn't Bring Anymore Options. Repo Needs An Update.

**Comment by anandpsdev** [comment]
Can you explain what exactly is not working

**Comment by IshwaranRudhara** [comment]
> Can you explain what exactly is not working

try hit start!

**Comment by anandpsdev** [comment]
@FristyFlakes [Your Issue has been fixed](https://github.com/Anandpskerala/TorrentSearcherBot/pull/5)
